In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('C:\Users\Shakila\Desktop\mobile.csv')
dataset.head(10)

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   
5           1859     0          0.5         1   3       0          22    0.7   
6           1821     0          1.7         0   4       1          10    0.8   
7           1954     0          0.5         1   0       0          24    0.8   
8           1445     1          0.5         0   0       0          53    0.7   
9            509     1          0.6         1   2       1           9    0.1   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   
5        164        1  ...       1004      1654  1067    17     1         10   
6        139        8  ...        381      1018  3220    13     8         18   
7        187        4  ...        512      1149   700    16     3          5   
8        174        7  ...        386       836  1099    17     1         20   
9         93        5  ...       1137      1224   513    19    10         12   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  
5        1             0     0            1  
6        1             0     1            3  
7        1             1     1            0  
8        1             0     0            0  
9        1             0     0            0  

[10 rows x 21 columns]

In [3]:
dataset.shape

(2000, 21)

In [4]:
X = dataset.drop('price_range', axis=1)
y = dataset['price_range']

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [6]:
from sklearn import svm
svm_clf = svm.SVC(kernel = 'linear')
svm_clf.fit(X_train, y_train)

SVC(kernel='linear')

In [7]:
from sklearn.metrics import accuracy_score, confusion_matrix
y_pred = svm_clf.predict(X_test)
c_m = confusion_matrix(y_test,y_pred)
print('confusion matrix:\n',c_m)

confusion matrix:
 [[165   3   0   0]
 [  3 129   2   0]
 [  0   6 145   6]
 [  0   0   0 141]]


In [8]:
a_s =accuracy_score(y_test,y_pred)
print('accuracy score = ',accuracy_score(y_test,y_pred))

accuracy score =  0.9666666666666667


In [9]:
svm_clf = svm.SVC(kernel = 'rbf')
svm_clf.fit(X_train, y_train)

SVC()

In [10]:
y_pred = svm_clf.predict(X_test)
c_m = confusion_matrix(y_test,y_pred)
print('confusion matrix:\n',c_m)

confusion matrix:
 [[164   4   0   0]
 [  3 127   4   0]
 [  0  14 126  17]
 [  0   0   1 140]]


In [11]:
a_s =accuracy_score(y_test,y_pred)
print('accuracy score = ',accuracy_score(y_test,y_pred))

accuracy score =  0.9283333333333333


In [12]:
svm_clf = svm.SVC(kernel = 'sigmoid')
svm_clf.fit(X_train, y_train)

SVC(kernel='sigmoid')

In [13]:
y_pred = svm_clf.predict(X_test)
c_m = confusion_matrix(y_test,y_pred)
print('confusion matrix:\n',c_m)

confusion matrix:
 [[106   0   0  62]
 [  6  13   0 115]
 [  1  27   0 129]
 [ 19 110   0  12]]


In [14]:
a_s =accuracy_score(y_test,y_pred)
print('accuracy score = ',accuracy_score(y_test,y_pred))

accuracy score =  0.21833333333333332


In [15]:
svm_clf = svm.SVC(kernel = 'poly', degree=3)
svm_clf.fit(X_train, y_train)

SVC(kernel='poly')

In [16]:
y_pred = svm_clf.predict(X_test)
c_m = confusion_matrix(y_test,y_pred)
print('confusion matrix:\n',c_m)

confusion matrix:
 [[168   0   0   0]
 [  6 124   4   0]
 [  0  10 134  13]
 [  0   0   2 139]]


In [17]:
a_s =accuracy_score(y_test,y_pred)
print('accuracy score = ',accuracy_score(y_test,y_pred))

accuracy score =  0.9416666666666667


In [18]:
svm_clf = svm.SVC(kernel = 'poly', degree=5)
svm_clf.fit(X_train, y_train)

SVC(degree=5, kernel='poly')

In [19]:
y_pred = svm_clf.predict(X_test)
c_m = confusion_matrix(y_test,y_pred)
print('confusion matrix:\n',c_m)

confusion matrix:
 [[168   0   0   0]
 [  7 124   3   0]
 [  0  10 132  15]
 [  0   0   1 140]]


In [20]:
a_s =accuracy_score(y_test,y_pred)
print('accuracy score = ',accuracy_score(y_test,y_pred))

accuracy score =  0.94


In [21]:
svm_clf = svm.SVC(C=0.1)
svm_clf.fit(X_train, y_train)

SVC(C=0.1)

In [22]:
y_pred = svm_clf.predict(X_test)
c_m = confusion_matrix(y_test,y_pred)
print('confusion matrix:\n',c_m)

confusion matrix:
 [[159   9   0   0]
 [  6 117  11   0]
 [  0  15 131  11]
 [  0   0   3 138]]


In [23]:
a_s =accuracy_score(y_test,y_pred)
print('accuracy score = ',accuracy_score(y_test,y_pred))

accuracy score =  0.9083333333333333


In [24]:
svm_clf = svm.SVC(C=0.5)
svm_clf.fit(X_train, y_train)

SVC(C=0.5)

In [25]:
y_pred = svm_clf.predict(X_test)
c_m = confusion_matrix(y_test,y_pred)
print('confusion matrix:\n',c_m)

confusion matrix:
 [[164   4   0   0]
 [  4 128   2   0]
 [  0  15 125  17]
 [  0   0   2 139]]


In [26]:
a_s =accuracy_score(y_test,y_pred)
print('accuracy score = ',accuracy_score(y_test,y_pred))

accuracy score =  0.9266666666666666


In [27]:
svm_clf = svm.SVC(C=5)
svm_clf.fit(X_train, y_train)

SVC(C=5)

In [28]:
y_pred = svm_clf.predict(X_test)
c_m = confusion_matrix(y_test,y_pred)
print('confusion matrix:\n',c_m)

confusion matrix:
 [[163   5   0   0]
 [  3 126   5   0]
 [  0  10 135  12]
 [  0   0   1 140]]


In [29]:
a_s =accuracy_score(y_test,y_pred)
print('accuracy score = ',accuracy_score(y_test,y_pred))

accuracy score =  0.94


In [30]:
svm_clf = svm.SVC(C=10)
svm_clf.fit(X_train, y_train)

SVC(C=10)

In [31]:
y_pred = svm_clf.predict(X_test)
c_m = confusion_matrix(y_test,y_pred)
print('confusion matrix:\n',c_m)

confusion matrix:
 [[162   6   0   0]
 [  3 127   4   0]
 [  0  10 136  11]
 [  0   0   1 140]]


In [32]:
a_s =accuracy_score(y_test,y_pred)
print('accuracy score = ',accuracy_score(y_test,y_pred))

accuracy score =  0.9416666666666667


In [33]:
print(dataset['battery_power'].min())
print(dataset['battery_power'].max())

501
1998


In [34]:
labels_3 = [0, 1, 2]
dataset['battery'] = pd.qcut(dataset['battery_power'], q=[0, 0.4, 0.7, 1], labels=labels_3)

In [35]:
dataset.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_width   ram  sc_h  sc_w  talk_time  three_g  \
0        188        2  ...       756  2549     9     7         19        0   
1        136        3  ...      1988  2631    17     3          7        1   
2        145        5  ...      1716  2603    11     2          9        1   
3        131        6  ...      1786  2769    16     8         11        1   
4        141        2  ...      1212  1411     8     2         15        1   

   touch_screen  wifi  price_range  battery  
0             0     1            1        0  
1             1     0            2        0  
2             1     0            2        0  
3             0     0            2        0  
4             1     0            1        2  

[5 rows x 22 columns]

In [36]:
X = dataset.drop(['price_range', 'battery_power'], axis=1)
y = dataset['price_range']

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [38]:
svm_clf = svm.SVC()
svm_clf.fit(X_train, y_train)

SVC()

In [39]:
y_pred = svm_clf.predict(X_test)
c_m = confusion_matrix(y_test,y_pred)
print('confusion matrix:\n',c_m)

confusion matrix:
 [[135  20   0   0]
 [ 11 113  24   0]
 [  0  23 102  20]
 [  0   0  27 125]]


In [40]:
a_s =accuracy_score(y_test,y_pred)
print('accuracy score = ',accuracy_score(y_test,y_pred))

accuracy score =  0.7916666666666666


In [41]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset_1 = pd.DataFrame()
  
dataset_1['blue']= le.fit_transform(dataset['blue'])
dataset_1['dual_sim']= le.fit_transform(dataset['dual_sim'])
dataset_1['four_g']= le.fit_transform(dataset['four_g'])
dataset_1['three_g']= le.fit_transform(dataset['three_g'])
dataset_1['wifi']= le.fit_transform(dataset['wifi'])

In [42]:
dataset_1.head(10)

blue  dual_sim  four_g  three_g  wifi
0     0         0       0        0     1
1     1         1       1        1     0
2     1         1       1        1     0
3     1         0       0        1     0
4     1         0       1        1     0
5     0         1       0        1     0
6     0         0       1        1     1
7     0         1       0        1     1
8     1         0       0        1     0
9     1         1       1        1     0

In [43]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder()

columnTransformer = ColumnTransformer([('encoder',
                                        OneHotEncoder(),
                                        [0])],
                                      remainder='passthrough')

In [44]:
dataset_1 = np.array(columnTransformer.fit_transform(dataset_1), dtype = np.str)

In [45]:
dataset_1

array([['1.0', '0.0', '0.0', '0.0', '0.0', '1.0'],
       ['0.0', '1.0', '1.0', '1.0', '1.0', '0.0'],
       ['0.0', '1.0', '1.0', '1.0', '1.0', '0.0'],
       ...,
       ['1.0', '0.0', '1.0', '1.0', '1.0', '0.0'],
       ['1.0', '0.0', '0.0', '1.0', '1.0', '1.0'],
       ['0.0', '1.0', '1.0', '1.0', '1.0', '1.0']], dtype='<U32')

In [46]:
dataset_1.shape

(2000, 6)

In [47]:
dataset_encode = dataset

In [48]:
pd.concat([dataset_encode, pd.DataFrame(dataset_1)], axis=1)

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  touch_screen  wifi  price_range  \
0       0.6        188        2  ...             0     1            1   
1       0.7        136        3  ...             1     0            2   
2       0.9        145        5  ...             1     0            2   
3       0.8        131        6  ...             0     0            2   
4       0.6        141        2  ...             1     0            1   
...     ...        ...      ...  ...           ...   ...          ...   
1995    0.8        106        6  ...             1     0            0   
1996    0.2        187        4  ...             1     1            2   
1997    0.7        108        8  ...             1     0            3   
1998    0.1        145        5  ...             1     1            0   
1999    0.9        168        6  ...             1     1            3   

      battery    0    1    2    3    4    5  
0           0  1.0  0.0  0.0  0.0  0.0  1.0  
1           0  0.0  1.0  1.0  1.0  1.0  0.0  
2           0  0.0  1.0  1.0  1.0  1.0  0.0  
3           0  0.0  1.0  0.0  0.0  1.0  0.0  
4           2  0.0  1.0  0.0  1.0  1.0  0.0  
...       ...  ...  ...  ...  ...  ...  ...  
1995        0  0.0  1.0  1.0  1.0  1.0  0.0  
1996        2  0.0  1.0  1.0  0.0  1.0  1.0  
1997        2  1.0  0.0  1.0  1.0  1.0  0.0  
1998        1  1.0  0.0  0.0  1.0  1.0  1.0  
1999        0  0.0  1.0  1.0  1.0  1.0  1.0  

[2000 rows x 28 columns]

In [49]:
dataset_encode = pd.concat([dataset_encode, pd.DataFrame(dataset_1)], axis=1)

In [50]:
dataset_encode

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  touch_screen  wifi  price_range  \
0       0.6        188        2  ...             0     1            1   
1       0.7        136        3  ...             1     0            2   
2       0.9        145        5  ...             1     0            2   
3       0.8        131        6  ...             0     0            2   
4       0.6        141        2  ...             1     0            1   
...     ...        ...      ...  ...           ...   ...          ...   
1995    0.8        106        6  ...             1     0            0   
1996    0.2        187        4  ...             1     1            2   
1997    0.7        108        8  ...             1     0            3   
1998    0.1        145        5  ...             1     1            0   
1999    0.9        168        6  ...             1     1            3   

      battery    0    1    2    3    4    5  
0           0  1.0  0.0  0.0  0.0  0.0  1.0  
1           0  0.0  1.0  1.0  1.0  1.0  0.0  
2           0  0.0  1.0  1.0  1.0  1.0  0.0  
3           0  0.0  1.0  0.0  0.0  1.0  0.0  
4           2  0.0  1.0  0.0  1.0  1.0  0.0  
...       ...  ...  ...  ...  ...  ...  ...  
1995        0  0.0  1.0  1.0  1.0  1.0  0.0  
1996        2  0.0  1.0  1.0  0.0  1.0  1.0  
1997        2  1.0  0.0  1.0  1.0  1.0  0.0  
1998        1  1.0  0.0  0.0  1.0  1.0  1.0  
1999        0  0.0  1.0  1.0  1.0  1.0  1.0  

[2000 rows x 28 columns]

In [51]:
X = dataset_encode.drop(['price_range', 'battery', 'blue', 'dual_sim', 'four_g', 'three_g', 'wifi'], axis=1)
y = dataset_encode['price_range']

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [53]:
svm_clf = svm.SVC()
svm_clf.fit(X_train, y_train)

SVC()

In [54]:
y_pred = svm_clf.predict(X_test)
c_m = confusion_matrix(y_test,y_pred)
print('confusion matrix:\n',c_m)

confusion matrix:
 [[144   1   0   0]
 [  3 149   3   0]
 [  0   9 134  10]
 [  0   0   4 143]]


In [55]:
a_s =accuracy_score(y_test,y_pred)
print('accuracy score = ',accuracy_score(y_test,y_pred))

accuracy score =  0.95


In [56]:
dataset.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_width   ram  sc_h  sc_w  talk_time  three_g  \
0        188        2  ...       756  2549     9     7         19        0   
1        136        3  ...      1988  2631    17     3          7        1   
2        145        5  ...      1716  2603    11     2          9        1   
3        131        6  ...      1786  2769    16     8         11        1   
4        141        2  ...      1212  1411     8     2         15        1   

   touch_screen  wifi  price_range  battery  
0             0     1            1        0  
1             1     0            2        0  
2             1     0            2        0  
3             0     0            2        0  
4             1     0            1        2  

[5 rows x 22 columns]

In [57]:
dataset_log = dataset

In [58]:
dataset_log['clock_speed'] = np.log2(dataset['clock_speed'])

In [59]:
dataset_log['battery_power'] = np.log2(dataset['battery_power'])

In [60]:
dataset_log['m_dep'] = np.log2(dataset['m_dep'])

In [61]:
dataset_log['talk_time'] = np.log2(dataset['talk_time'])

In [62]:
dataset_log.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0       9.717676     0     1.137504         0   1       0           7   
1       9.995767     1    -1.000000         1   0       1          53   
2       9.136991     1    -1.000000         1   2       1          41   
3       9.264443     1     1.321928         0   0       0          10   
4      10.830515     1     0.263034         0  13       1          44   

      m_dep  mobile_wt  n_cores  ...  px_width   ram  sc_h  sc_w  talk_time  \
0 -0.736966        188        2  ...       756  2549     9     7   4.247928   
1 -0.514573        136        3  ...      1988  2631    17     3   2.807355   
2 -0.152003        145        5  ...      1716  2603    11     2   3.169925   
3 -0.321928        131        6  ...      1786  2769    16     8   3.459432   
4 -0.736966        141        2  ...      1212  1411     8     2   3.906891   

   three_g  touch_screen  wifi  price_range  battery  
0        0             0     1            1        0  
1        1             1     0            2        0  
2        1             1     0            2        0  
3        1             0     0            2        0  
4        1             1     0            1        2  

[5 rows x 22 columns]

In [63]:
X = dataset_log.drop(['price_range', 'battery'], axis=1)
y = dataset_log['price_range']

In [64]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [65]:
svm_clf = svm.SVC()
svm_clf.fit(X_train, y_train)

SVC()

In [66]:
y_pred = svm_clf.predict(X_test)
c_m = confusion_matrix(y_test,y_pred)
print('confusion matrix:\n',c_m)

confusion matrix:
 [[130  27   0   0]
 [ 17 112  12   0]
 [  0  25 104  34]
 [  0   0  12 127]]


In [67]:
a_s =accuracy_score(y_test,y_pred)
print('accuracy score = ',accuracy_score(y_test,y_pred))

accuracy score =  0.7883333333333333


In [68]:
dataset_area=dataset

In [69]:
dataset_area['area'] = dataset['px_height']*dataset['px_width']
dataset_area.head(10)

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0       9.717676     0     1.137504         0   1       0           7   
1       9.995767     1    -1.000000         1   0       1          53   
2       9.136991     1    -1.000000         1   2       1          41   
3       9.264443     1     1.321928         0   0       0          10   
4      10.830515     1     0.263034         0  13       1          44   
5      10.860311     0    -1.000000         1   3       0          22   
6      10.830515     0     0.765535         0   4       1          10   
7      10.932215     0    -1.000000         1   0       0          24   
8      10.496854     1    -1.000000         0   0       0          53   
9       8.991522     1    -0.736966         1   2       1           9   

      m_dep  mobile_wt  n_cores  ...   ram  sc_h  sc_w  talk_time  three_g  \
0 -0.736966        188        2  ...  2549     9     7   4.247928        0   
1 -0.514573        136        3  ...  2631    17     3   2.807355        1   
2 -0.152003        145        5  ...  2603    11     2   3.169925        1   
3 -0.321928        131        6  ...  2769    16     8   3.459432        1   
4 -0.736966        141        2  ...  1411     8     2   3.906891        1   
5 -0.514573        164        1  ...  1067    17     1   3.321928        1   
6 -0.321928        139        8  ...  3220    13     8   4.169925        1   
7 -0.321928        187        4  ...   700    16     3   2.321928        1   
8 -0.514573        174        7  ...  1099    17     1   4.321928        1   
9 -3.321928         93        5  ...   513    19    10   3.584963        1   

   touch_screen  wifi  price_range  battery     area  
0             0     1            1        0    15120  
1             1     0            2        0  1799140  
2             1     0            2        0  2167308  
3             0     0            2        0  2171776  
4             1     0            1        2  1464096  
5             0     0            1        2  1660616  
6             0     1            3        2   387858  
7             1     1            0        2   588288  
8             0     0            0        1   322696  
9             0     0            0        0  1391688  

[10 rows x 23 columns]

In [70]:
X = dataset_area.drop(['price_range', 'battery'], axis=1)
y = dataset_area['price_range']

In [71]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [72]:
svm_clf = svm.SVC()
svm_clf.fit(X_train, y_train)

SVC()

In [73]:
y_pred = svm_clf.predict(X_test)
c_m = confusion_matrix(y_test,y_pred)
print('confusion matrix:\n',c_m)

confusion matrix:
 [[97 27  0 32]
 [82 26  0 37]
 [81 24  0 39]
 [66 30  0 59]]


In [74]:
a_s =accuracy_score(y_test,y_pred)
print('accuracy score = ',accuracy_score(y_test,y_pred))

accuracy score =  0.30333333333333334


In [75]:
dataset_all = dataset_encode

In [76]:
dataset_all['area'] = dataset_area['area']

In [77]:
dataset_all['clock_speed'] = dataset_log['clock_speed']
dataset_all['m_dep'] = dataset_log['m_dep']
dataset_all['talk_time'] = dataset_log['talk_time']

In [78]:
dataset_all.head(10)

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0            842     0     1.137504         0   1       0           7   
1           1021     1    -1.000000         1   0       1          53   
2            563     1    -1.000000         1   2       1          41   
3            615     1     1.321928         0   0       0          10   
4           1821     1     0.263034         0  13       1          44   
5           1859     0    -1.000000         1   3       0          22   
6           1821     0     0.765535         0   4       1          10   
7           1954     0    -1.000000         1   0       0          24   
8           1445     1    -1.000000         0   0       0          53   
9            509     1    -0.736966         1   2       1           9   

      m_dep  mobile_wt  n_cores  ...  wifi  price_range  battery    0    1  \
0 -0.736966        188        2  ...     1            1        0  1.0  0.0   
1 -0.514573        136        3  ...     0            2        0  0.0  1.0   
2 -0.152003        145        5  ...     0            2        0  0.0  1.0   
3 -0.321928        131        6  ...     0            2        0  0.0  1.0   
4 -0.736966        141        2  ...     0            1        2  0.0  1.0   
5 -0.514573        164        1  ...     0            1        2  1.0  0.0   
6 -0.321928        139        8  ...     1            3        2  1.0  0.0   
7 -0.321928        187        4  ...     1            0        2  1.0  0.0   
8 -0.514573        174        7  ...     0            0        1  0.0  1.0   
9 -3.321928         93        5  ...     0            0        0  0.0  1.0   

     2    3    4    5     area  
0  0.0  0.0  0.0  1.0    15120  
1  1.0  1.0  1.0  0.0  1799140  
2  1.0  1.0  1.0  0.0  2167308  
3  0.0  0.0  1.0  0.0  2171776  
4  0.0  1.0  1.0  0.0  1464096  
5  1.0  0.0  1.0  0.0  1660616  
6  0.0  1.0  1.0  1.0   387858  
7  1.0  0.0  1.0  1.0   588288  
8  0.0  0.0  1.0  0.0   322696  
9  1.0  1.0  1.0  0.0  1391688  

[10 rows x 29 columns]

In [79]:
X = dataset_all.drop(['price_range', 'battery_power'], axis=1)
y = dataset_all['price_range']

In [80]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [81]:
svm_clf = svm.SVC()
svm_clf.fit(X_train, y_train)

SVC()

In [82]:
y_pred = svm_clf.predict(X_test)
c_m = confusion_matrix(y_test,y_pred)
print('confusion matrix:\n',c_m)

confusion matrix:
 [[85 43  0 40]
 [53 44  0 50]
 [66 33  0 42]
 [49 37  0 58]]
