In [158]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.svm import SVC
import seaborn as sb
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import OneHotEncoder

In [159]:
from google.colab import files
uploaded = files.upload()
traindf= pd.read_csv('train.csv') 

Saving train.csv to train (1).csv


In [313]:
traindf= pd.read_csv('train.csv')

In [314]:
traindf.head()

battery_power  blue  clock_speed  ...  touch_screen  wifi  price_range
0            842     0          2.2  ...             0     1            1
1           1021     1          0.5  ...             1     0            2
2            563     1          0.5  ...             1     0            2
3            615     1          2.5  ...             0     0            2
4           1821     1          1.2  ...             1     0            1

[5 rows x 21 columns]

In [315]:
traindf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

In [316]:
X = traindf.drop(['price_range'], axis=1)
y = traindf['price_range']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=22, shuffle=True)

In [317]:
svmrbf = SVC()
svmrbf.fit(X_train, y_train)
svmrbf.score(X_test, y_test)

0.9533333333333334

In [318]:
y_pred = svmrbf.predict(X_test)
CM = confusion_matrix(y_test, y_pred)
print(CM)

[[141   3   0   0]
 [  7 138   0   0]
 [  0   7 143   8]
 [  0   0   3 150]]


In [319]:
svmlinear = SVC(kernel = 'linear')
svmlinear.fit(X_train, y_train)
svmlinear.score(X_test, y_test)

0.9666666666666667

In [320]:
svmpoly = SVC(kernel = 'poly')
svmpoly.fit(X_train, y_train)
svmpoly.score(X_test, y_test)

0.955

In [321]:
svmsigmoid = SVC(kernel = 'sigmoid')
svmsigmoid.fit(X_train, y_train)
svmsigmoid.score(X_test, y_test)

0.185

In [322]:
svmrbf2 = SVC(C = 0.01)
svmrbf2.fit(X_train, y_train)
svmrbf2.score(X_test, y_test)

0.5816666666666667

In [323]:
svmrbf3 = SVC(C = 100)
svmrbf3.fit(X_train, y_train)
svmrbf3.score(X_test, y_test)

0.9683333333333334

In [324]:
svmlinear2 = SVC(kernel = 'linear',C = 0.01)
svmlinear2.fit(X_train, y_train)
svmlinear2.score(X_test, y_test)

0.9683333333333334

In [325]:
svmlinear3 = SVC(kernel = 'linear',C = 100)
svmlinear3.fit(X_train, y_train)
svmlinear3.score(X_test, y_test)

0.9716666666666667

In [326]:
svmpoly2 = SVC(kernel = 'poly',C = 0.01)
svmpoly2.fit(X_train, y_train)
svmpoly2.score(X_test, y_test)

0.7633333333333333

In [327]:
svmpoly3 = SVC(kernel = 'poly',C = 100)
svmpoly3.fit(X_train, y_train)
svmpoly3.score(X_test, y_test)

0.9783333333333334

In [328]:
svmsigmoid2 = SVC(kernel = 'sigmoid',C = 0.01)
svmsigmoid2.fit(X_train, y_train)
svmsigmoid2.score(X_test, y_test)

0.24

In [329]:
svmsigmoid3 = SVC(kernel = 'sigmoid',C = 100)
svmsigmoid3.fit(X_train, y_train)
svmsigmoid3.score(X_test, y_test)

0.17

In [330]:
svmrbf4 = SVC(gamma=0.000005)
svmrbf4.fit(X_train, y_train)
svmrbf4.score(X_test, y_test)

0.9466666666666667

In [331]:
svmlinear4 = SVC(kernel = 'linear',gamma=0.000005)
svmlinear4.fit(X_train, y_train)
svmlinear4.score(X_test, y_test)

0.9666666666666667

In [332]:
svmpoly4 = SVC(kernel = 'poly',gamma=0.000005)
svmpoly4.fit(X_train, y_train)
svmpoly4.score(X_test, y_test)

0.9666666666666667

In [333]:
svmsigmoid4 = SVC(kernel = 'sigmoid',gamma=0.000005)
svmsigmoid4.fit(X_train, y_train)
svmsigmoid4.score(X_test, y_test)

0.24

In [334]:
#.........................

In [335]:
traindf.head()

battery_power  blue  clock_speed  ...  touch_screen  wifi  price_range
0            842     0          2.2  ...             0     1            1
1           1021     1          0.5  ...             1     0            2
2            563     1          0.5  ...             1     0            2
3            615     1          2.5  ...             0     0            2
4           1821     1          1.2  ...             1     0            1

[5 rows x 21 columns]

In [336]:
traindf.n_cores.unique()

array([2, 3, 5, 6, 1, 8, 4, 7])

In [337]:
dfblue= pd.get_dummies(traindf.blue, prefix='blue')
dfdual_sim = pd.get_dummies(traindf.dual_sim, prefix='dual_sim')
dftouch_screen= pd.get_dummies(traindf.touch_screen, prefix='touch_screen')
dfwifi = pd.get_dummies(traindf.wifi, prefix='wifi')
dfn_cores = pd.get_dummies(traindf.n_cores, prefix='n_cores')

In [338]:
df= pd.concat([dfblue, dfdual_sim,dftouch_screen,dfwifi,dfn_cores], axis=1)

In [339]:
df2=pd.concat([traindf,df], axis=1)

In [340]:
A=['blue','dual_sim','touch_screen','wifi','n_cores']

In [341]:
df2.drop(A, axis = 1)

battery_power  clock_speed  fc  ...  n_cores_6  n_cores_7  n_cores_8
0               842          2.2   1  ...          0          0          0
1              1021          0.5   0  ...          0          0          0
2               563          0.5   2  ...          0          0          0
3               615          2.5   0  ...          1          0          0
4              1821          1.2  13  ...          0          0          0
...             ...          ...  ..  ...        ...        ...        ...
1995            794          0.5   0  ...          1          0          0
1996           1965          2.6   0  ...          0          0          0
1997           1911          0.9   1  ...          0          0          1
1998           1512          0.9   4  ...          0          0          0
1999            510          2.0   5  ...          1          0          0

[2000 rows x 32 columns]

In [342]:
X = df2.drop(['price_range'], axis=1)
y =df2['price_range']

In [343]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=22, shuffle=True)

In [344]:
svmrbf = SVC()
svmrbf.fit(X_train, y_train)
svmrbf.score(X_test, y_test)

0.9583333333333334

In [345]:
traindf['battery_power'].describe()

count    2000.000000
mean     1238.518500
std       439.418206
min       501.000000
25%       851.750000
50%      1226.000000
75%      1615.250000
max      1998.000000
Name: battery_power, dtype: float64

In [346]:
#traindf['battery_power_binning']=pd.qcut(traindf['battery_power'], q=4)

In [347]:
#traindf['battery_power_binning'].value_counts()

In [348]:
min_value = traindf['battery_power'].min()
max_value = traindf['battery_power'].max()
print(min_value)
print(max_value)

501
1998


In [349]:
bins = np.linspace(min_value,max_value,4)
bins

array([ 501., 1000., 1499., 1998.])

In [350]:
labels = [1, 2, 3]

In [351]:
traindf['battery'] = pd.cut(traindf['battery_power'], bins=bins, labels=labels, include_lowest=True)

In [352]:
traindf.head()

battery_power  blue  clock_speed  ...  wifi  price_range  battery
0            842     0          2.2  ...     1            1        1
1           1021     1          0.5  ...     0            2        2
2            563     1          0.5  ...     0            2        1
3            615     1          2.5  ...     0            2        1
4           1821     1          1.2  ...     0            1        3

[5 rows x 22 columns]

In [353]:
X = traindf.drop(['price_range','battery_power'], axis=1)

In [354]:
#X = traindf.drop(['price_range'], axis=1)
y =traindf['price_range']

In [355]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=22, shuffle=True)

In [356]:
svmrbf = SVC()
svmrbf.fit(X_train, y_train)
svmrbf.score(X_test, y_test)

0.7983333333333333

In [357]:
bins = np.linspace(min_value,max_value,10)
bins

array([ 501.        ,  667.33333333,  833.66666667, 1000.        ,
       1166.33333333, 1332.66666667, 1499.        , 1665.33333333,
       1831.66666667, 1998.        ])

In [358]:
labels = [1, 2,3,4,5,6,7,8,9]

In [359]:
traindf = traindf.drop(['battery'], axis=1)


In [360]:
traindf['battery'] = pd.cut(traindf['battery_power'], bins=bins, labels=labels, include_lowest=True)

In [361]:
traindf.head()

battery_power  blue  clock_speed  ...  wifi  price_range  battery
0            842     0          2.2  ...     1            1        3
1           1021     1          0.5  ...     0            2        4
2            563     1          0.5  ...     0            2        1
3            615     1          2.5  ...     0            2        1
4           1821     1          1.2  ...     0            1        8

[5 rows x 22 columns]

In [362]:
#X = traindf.drop(['price_range','battery_power'], axis=1)

In [363]:
#X = traindf.drop(['price_range'], axis=1)
X = traindf.drop(['price_range','battery_power'], axis=1)
y =traindf['price_range']

In [364]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=22, shuffle=True)

In [365]:
svmrbf = SVC()
svmrbf.fit(X_train, y_train)
svmrbf.score(X_test, y_test)

0.7983333333333333

In [366]:
bins = np.linspace(min_value,max_value,30)
bins

array([ 501.        ,  552.62068966,  604.24137931,  655.86206897,
        707.48275862,  759.10344828,  810.72413793,  862.34482759,
        913.96551724,  965.5862069 , 1017.20689655, 1068.82758621,
       1120.44827586, 1172.06896552, 1223.68965517, 1275.31034483,
       1326.93103448, 1378.55172414, 1430.17241379, 1481.79310345,
       1533.4137931 , 1585.03448276, 1636.65517241, 1688.27586207,
       1739.89655172, 1791.51724138, 1843.13793103, 1894.75862069,
       1946.37931034, 1998.        ])

In [367]:
labels = [1, 2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29]

In [368]:
traindf = traindf.drop(['battery'], axis=1)


In [369]:
traindf['battery'] = pd.cut(traindf['battery_power'], bins=bins, labels=labels, include_lowest=True)

In [370]:
X = traindf.drop(['price_range'], axis=1)
#X = traindf.drop(['price_range','battery_power'], axis=1)
y =traindf['price_range']

In [371]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=22, shuffle=True)

In [372]:
svmrbf = SVC()
svmrbf.fit(X_train, y_train)
svmrbf.score(X_test, y_test)

0.9533333333333334

In [373]:
#traindf['area']=traindf['px_height']*traindf['px_width']

In [374]:
#traindf = traindf.drop(['battery'], axis=1)

In [375]:
#X = traindf.drop(['price_range'], axis=1)
#y =traindf['price_range']

In [376]:
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=22, shuffle=True)

In [377]:
#svmrbf = SVC()
#svmrbf.fit(X_train, y_train)
#svmrbf.score(X_test, y_test)
#0.2966666666666667

In [378]:
traindf.head()

battery_power  blue  clock_speed  ...  wifi  price_range  battery
0            842     0          2.2  ...     1            1        7
1           1021     1          0.5  ...     0            2       11
2            563     1          0.5  ...     0            2        2
3            615     1          2.5  ...     0            2        3
4           1821     1          1.2  ...     0            1       26

[5 rows x 22 columns]

In [379]:
 traindf['lcd'] = (np.sqrt(traindf['sc_h']**2+traindf['sc_w']**2)).round(2)

In [380]:
traindf.head()

battery_power  blue  clock_speed  dual_sim  ...  wifi  price_range  battery    lcd
0            842     0          2.2         0  ...     1            1        7  11.40
1           1021     1          0.5         1  ...     0            2       11  17.26
2            563     1          0.5         1  ...     0            2        2  11.18
3            615     1          2.5         0  ...     0            2        3  17.89
4           1821     1          1.2         0  ...     0            1       26   8.25

[5 rows x 23 columns]

In [381]:
#X = traindf.drop(['price_range','area','sc_w','sc_h'], axis=1)
X = traindf.drop(['price_range'], axis=1)
y =traindf['price_range']

In [382]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=22, shuffle=True)

In [383]:
svmrbf = SVC()
svmrbf.fit(X_train, y_train)
svmrbf.score(X_test, y_test)

0.9533333333333334

In [384]:
#...........

In [385]:
df6= df2

In [386]:
bins = np.linspace(min_value,max_value,30)
labels = [1, 2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29]
df6['battery'] = pd.cut(df6['battery_power'], bins=bins, labels=labels, include_lowest=True)
df6['lcd'] = (np.sqrt(df6['sc_h']**2+df6['sc_w']**2)).round(2)


In [389]:
X = df6.drop(['price_range'], axis=1)
y =df6['price_range']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=22, shuffle=True)

In [392]:
svmrbf = SVC(kernel = 'linear')
svmrbf.fit(X_train, y_train)
svmrbf.score(X_test, y_test)

0.9716666666666667